name: 打包自动化部署

on:
  push:
    branches:
      - master

jobs:
  build:
    # runs-on 指定job任务运行需要的虚拟机环境 必填
    runs-on: ubuntu-latest
    steps:
      # 获取源码
      - name: 迁出代码
        # 使用action 库 actions/checkout 获取源码
        uses: actions/checkout@master
      # 安装node10

      - name: 安装 nodejs
        # 使用action 库  actions/setup-node 安装node
        uses: actions/setup-node@v1
        with:
          node-version: 14.0.0
      # 安装依赖
      - name: 安装依赖
        run: npm install

      # 打包
      - name: 打包
        run: npm run build

      # 上传到阿里云  ssh 命令行方式
      - name: 发布到阿里云
        users: easingthemes/ssh-depploy@v2.1.1
        env:
          # 私钥
          SSH_PRIVATE_KEY: ${{ SECRETS.PRIVATE_KEY}}
          # scp 参数
          ARGS: "-avzr --delete"
          # 源目录
          SOURCE: 'vite-ts-admin',
          # 服务器 ip
          remote_host: "47.98.252.43"
          # 用户
          REMOTE_USER: "root"
          # 目标地址
          TARGET: "/root/vue-in-action"